name: show_hub
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  http: ^1.2.0
  dartz: ^0.10.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.0.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true



  assets:
    - assets/Images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
